apiVersion: v1
kind: Secret
metadata:
  name: tickify-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "REPLACE_WITH_YOUR_CONNECTION_STRING"

  Jwt__IssuerSigningKey: "SUPER_SECRET_KEY_123456789_SUPER_LONG"
  Jwt__ValidIssuer: "tickify-api"
  Jwt__ValidAudience: "tickify-users"