apiVersion: v1
kind: Secret
metadata:
  name: tickify-secret
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "REPLACE_WITH_RDS_CONNECTION_STRING"
  Jwt__IssuerSigningKey: "REPLACE_WITH_STRONG_RANDOM_SECRET_MIN_32_CHARS"
  Jwt__ValidIssuer: "Tickify"
  Jwt__ValidAudience: "TickifyUsers"
  SEEDING__ADMINPASSWORD: "REPLACE_WITH_ADMIN_PASSWORD"
  SEEDING__SUPERADMINPASSWORD: "REPLACE_WITH_SUPERADMIN_PASSWORD"
  AWS__BucketName: "REPLACE_WITH_S3_BUCKET_NAME"
