apiVersion: v1
kind: Service
metadata:
  name: tickify-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/load-balancer-source-ranges: "91.147.200.214/32"
spec:
  type: LoadBalancer
  selector:
    app: tickify-backend
  ports:
    - port: 80
      targetPort: 8080